// 水果資料庫（梨山高山水果排在前面）
const fruitsData = [

  // ===== 梨山高山水果（主打）=====
  {
    id: 13,
    name: "梨山牛奶水蜜桃",
    emoji: "🍑",
    price: 850,
    unit: "15顆/精裝禮盒",
    category: "梨山高山",
    season: "7月上旬-8月上旬",
    origin: "台中梨山",
    sugar: "14-18°Brix",
    description: "品種「上海蜜」，謝家草生栽培、手工套袋每一顆，山泉水灌溉長大。謝博士只在糖度達14度那天才採收，果皮薄如紙、咬下甜汁溢出、果肉柔嫩入口即化。一年只有短短三週，7月開始預購，搶完即止，錯過只能等明年。",
    tags: ["精品", "高山限定", "預購"],
    rating: 5.0,
    reviews: 312,
    inStock: true
  },
  {
    id: 14,
    name: "梨山牛奶西瓜李",
    emoji: "🍑",
    price: 650,
    unit: "約2公斤/盒",
    category: "梨山高山",
    season: "6月中旬-6月下旬",
    origin: "台中梨山",
    sugar: "16-20°Brix",
    description: "外皮青綠帶白色條紋，像縮小版西瓜；果肉奶白柔滑，咬下是16度以上的清甜蜜汁，這是梨山獨有的稀有品種。謝爸爸手工套袋每一顆，每年就這兩週，連續大雨會讓一整季心血泡湯——能買到就是運氣。",
    tags: ["限量", "高山限定", "稀有品種"],
    rating: 4.9,
    reviews: 178,
    inStock: true
  },
  {
    id: 15,
    name: "梨山雪梨 8大粒禮盒",
    emoji: "🍐",
    price: 950,
    unit: "8大粒/禮盒",
    category: "梨山高山",
    season: "11月下旬-12月",
    origin: "台中梨山",
    sugar: "12-15°Brix",
    description: "謝爸爸照顧這棵梨樹二十年，每顆親手套白紙袋讓果皮在秋霧裡長出雪白光澤。果核小到兩根手指能夾起，果肉卻多到快撐破——爽脆清甜不留渣，甜度穩定達13度以上。11月下旬短短三週，限量預購完即停售。",
    tags: ["精品", "高山限定", "禮盒"],
    rating: 4.9,
    reviews: 198,
    inStock: true
  },
  {
    id: 16,
    name: "梨山雪梨 5特粒禮盒",
    emoji: "🍐",
    price: 1800,
    unit: "5特粒/禮盒（單顆約30-32兩）",
    category: "梨山高山",
    season: "11月下旬-12月",
    origin: "台中梨山",
    sugar: "13-16°Brix",
    description: "全園數百顆裡最後挑出的前3%。單顆重達30兩，放在掌心沉甸甸像顆小西瓜；謝博士每顆都用糖度計確認超過14度才封箱。拆開禮盒那一刻，連不愛吃水果的長輩也會停下來說話。",
    tags: ["限量", "頂級", "送禮首選"],
    rating: 5.0,
    reviews: 89,
    inStock: true
  },
  {
    id: 17,
    name: "梨山甜柿 12粒禮盒",
    emoji: "🟠",
    price: 650,
    unit: "12粒/禮盒",
    category: "梨山高山",
    season: "11月-12月",
    origin: "台中梨山",
    sugar: "16-20°Brix",
    description: "一般柿子需要脫澀才能吃，梨山甜柿不用——這是品種與海拔共同給的天然特權。謝家草生栽培，不噴除草劑，讓甜柿在秋霧寒氣裡自然把糖存進去。橙黃飽滿、咬下脆甜多汁，達16度以上才出貨。11月到12月短短兩個月，過了就結束。",
    tags: ["高山限定", "當季", "禮盒"],
    rating: 4.9,
    reviews: 143,
    inStock: true
  },
  {
    id: 18,
    name: "梨山甜柿 8特粒禮盒",
    emoji: "🟠",
    price: 1000,
    unit: "8特粒/精裝禮盒",
    category: "梨山高山",
    season: "11月-12月",
    origin: "台中梨山",
    sugar: "18-22°Brix",
    description: "八顆從全園數千粒裡親手挑出的特選，每一顆謝博士都用糖度計確認達18度以上才進盒。拆開禮盒那一刻，橙黃色的光芒和甜柿特有的木質甜香一起湧出——這是能讓長輩說「這輩子吃過最好的柿子」的那種禮物。",
    tags: ["精品", "限量", "送禮首選"],
    rating: 5.0,
    reviews: 96,
    inStock: true
  },
  {
    id: 19,
    name: "梨山寶島甘露梨",
    emoji: "🍐",
    price: 780,
    unit: "8粒/禮盒",
    category: "梨山高山",
    season: "9月中旬-10月中旬",
    origin: "台中梨山",
    sugar: "13-16°Brix",
    description: "「甘露」是謝爸爸取的名：品種「寶島甘露」，以山泉水滋養，每顆親手套袋護色。果肉細白如脂，核小肉多，甜度穩定達13度以上，梨汁豐沛、毫無澀感。從採收到出貨48小時內，秋天的霧氣和涼意就在這顆梨裡。",
    tags: ["當季", "高山限定", "精品"],
    rating: 4.8,
    reviews: 124,
    inStock: true
  },
  {
    id: 20,
    name: "梨山蜜蘋果",
    emoji: "🍎",
    price: 720,
    unit: "約2公斤/盒",
    category: "梨山高山",
    season: "10月下旬-11月中旬",
    origin: "台中梨山",
    sugar: "14-16°Brix",
    description: "謝博士的農業博士論文研究蘋果糖分累積機制，現在他把論文種在梨山。海拔2000公尺的日夜寒差讓糖以山梨醇形式結晶在果核周圍——切開剖面那片半透明的蜜汁，是蘋果自己釀出來的甜，不是加進去的。手工套袋、草生栽培，10月下旬限量開訂，三週後本季結束。",
    tags: ["高山限定", "當季", "蜜汁品種"],
    rating: 4.9,
    reviews: 167,
    inStock: true
  },

  // ===== 台灣各地水果 =====
  {
    id: 1,
    name: "台灣芒果",
    emoji: "🥭",
    price: 380,
    unit: "3公斤/箱",
    category: "熱帶水果",
    season: "5月-8月",
    origin: "屏東枋山",
    sugar: "18-22°Brix",
    description: "屏東枋山金煌芒果，果核薄如刀片、果肉厚實無纖維，切開那一刀甜香撲鼻，一口下去像在飲熱帶陽光。",
    tags: ["熱銷", "當季"],
    rating: 4.9,
    reviews: 328,
    inStock: true
  },
  {
    id: 2,
    name: "玉荷包荔枝",
    emoji: "🍒",
    price: 450,
    unit: "2公斤/盒",
    category: "夏季水果",
    season: "6月-7月",
    origin: "高雄大樹",
    sugar: "18-20°Brix",
    description: "高雄大樹玉荷包，殼薄到透光、果肉白嫩如凍，剝開的瞬間甜香噴出，每年只有一個月，搶不到就等明年。",
    tags: ["限量", "當季"],
    rating: 4.8,
    reviews: 215,
    inStock: true
  },
  {
    id: 3,
    name: "鳳梨釋迦",
    emoji: "🍈",
    price: 520,
    unit: "4顆/盒",
    category: "熱帶水果",
    season: "10月-2月",
    origin: "台東太麻里",
    sugar: "20-24°Brix",
    description: "台東太麻里鳳梨釋迦，挖開厚實果殼，奶白果肉帶著鳳梨的幽香，甜度破 20 度卻不膩，挖一勺送禮，長輩保證記住你。",
    tags: ["精品", "禮盒"],
    rating: 4.9,
    reviews: 189,
    inStock: true
  },
  {
    id: 4,
    name: "草莓",
    emoji: "🍓",
    price: 320,
    unit: "1公斤/盒",
    category: "溫帶水果",
    season: "12月-4月",
    origin: "苗栗大湖",
    sugar: "10-14°Brix",
    description: "苗栗大湖香水草莓，尖端深紅、香氣從遠處就飄來，牙齒輕咬的瞬間酸甜爆漿，吃第一顆就停不下來。",
    tags: ["熱銷", "當季"],
    rating: 4.7,
    reviews: 412,
    inStock: true
  },
  {
    id: 5,
    name: "香蕉",
    emoji: "🍌",
    price: 120,
    unit: "1串/約1.5公斤",
    category: "熱帶水果",
    season: "全年",
    origin: "南投集集",
    sugar: "14-18°Brix",
    description: "南投集集台灣蕉，果皮轉黃出現黑斑時甜度最高，綿密細緻、香氣十足，運動補給或是下午三點的續命點心，都靠它。",
    tags: ["天天到貨"],
    rating: 4.6,
    reviews: 567,
    inStock: true
  },
  {
    id: 6,
    name: "愛文芒果",
    emoji: "🥭",
    price: 420,
    unit: "4公斤/箱",
    category: "熱帶水果",
    season: "5月-8月",
    origin: "台南玉井",
    sugar: "16-20°Brix",
    description: "台南玉井愛文芒果，果皮紅豔如夕陽，果肉橙黃細膩不留纖維，是台灣芒果界的天花板，切開就已經贏了。",
    tags: ["熱銷", "當季"],
    rating: 4.8,
    reviews: 298,
    inStock: true
  },
  {
    id: 7,
    name: "巨峰葡萄",
    emoji: "🍇",
    price: 280,
    unit: "1公斤/盒",
    category: "溫帶水果",
    season: "7月-10月",
    origin: "彰化溪湖",
    sugar: "16-20°Brix",
    description: "彰化溪湖巨峰葡萄，每顆都像小拳頭一樣飽滿，輕輕一捏果皮就分離，咬下去甜汁四溢，秋天不吃一串這個，就浪費了季節。",
    tags: ["當季"],
    rating: 4.7,
    reviews: 156,
    inStock: true
  },
  {
    id: 8,
    name: "鳳梨",
    emoji: "🍍",
    price: 160,
    unit: "1顆/約2公斤",
    category: "熱帶水果",
    season: "全年",
    origin: "嘉義民雄",
    sugar: "14-18°Brix",
    description: "嘉義民雄金鑽鳳梨，切開不刺口、無渣多汁，甜度穩定在 14 度以上，以前對鳳梨過敏的人通常也能放心吃，台灣農改站的驕傲。",
    tags: ["天天到貨", "熱銷"],
    rating: 4.8,
    reviews: 445,
    inStock: true
  },
  {
    id: 9,
    name: "木瓜",
    emoji: "🧡",
    price: 180,
    unit: "1顆/約1.5公斤",
    category: "熱帶水果",
    season: "全年",
    origin: "台南玉井",
    sugar: "12-16°Brix",
    description: "台南玉井木瓜，橙紅色果肉像把整個夕陽裝進去，質地細緻入口即化，空腹早餐或飯後一片，木瓜酵素默默幫你顧腸胃。",
    tags: ["健康首選"],
    rating: 4.6,
    reviews: 189,
    inStock: true
  },
  {
    id: 10,
    name: "西瓜",
    emoji: "🍉",
    price: 260,
    unit: "半顆/約5公斤",
    category: "夏季水果",
    season: "4月-9月",
    origin: "花蓮壽豐",
    sugar: "10-13°Brix",
    description: "花蓮壽豐無籽西瓜，剖開紅豔豔的瞬間就想立刻啃下去，水分多到流汁，夏天沒有冰西瓜，算什麼夏天。",
    tags: ["當季", "消暑"],
    rating: 4.7,
    reviews: 234,
    inStock: true
  },
  {
    id: 11,
    name: "百香果",
    emoji: "🍋",
    price: 240,
    unit: "1公斤/約15顆",
    category: "熱帶水果",
    season: "7月-11月",
    origin: "南投埔里",
    sugar: "14-18°Brix",
    description: "南投埔里百香果，搖一搖有水聲的是最熟的，剪開一股濃香衝出來，酸甜汁液直接喝或淋在優格上，兩種吃法都上癮。",
    tags: ["當季", "香氣濃"],
    rating: 4.8,
    reviews: 178,
    inStock: false
  },
  {
    id: 12,
    name: "蓮霧",
    emoji: "🔴",
    price: 350,
    unit: "2公斤/盒",
    category: "熱帶水果",
    season: "11月-2月",
    origin: "屏東林邊",
    sugar: "12-16°Brix",
    description: "屏東林邊黑珍珠蓮霧，皮色深紅油亮，咬下去清脆的聲音跟口感一樣讓人愉快，回甘的甜味在喉嚨停很久，拿去送禮比什麼都有面子。",
    tags: ["限量", "禮盒"],
    rating: 4.9,
    reviews: 267,
    inStock: true
  },

];

// 水果知識資料
const fruitKnowledge = [
  {
    id: 1,
    fruit: "芒果",
    emoji: "🥭",
    title: "芒果的營養秘密",
    category: "營養知識",
    content: "芒果富含維生素A、C、E及β-胡蘿蔔素，每100克含維生素C約36mg。其中的芒果苷具有抗氧化功效，適量食用有助於護眼、提升免疫力。",
    tips: ["挑選時以果皮光滑、按壓有彈性為佳", "放室溫等待轉黃再冷藏，甜度更高", "切忌未熟時冷藏，會影響後熟過程"]
  },
  {
    id: 2,
    fruit: "草莓",
    emoji: "🍓",
    title: "草莓挑選完全攻略",
    category: "挑選技巧",
    content: "草莓是維生素C的絕佳來源，每100克含量高達60mg，超過柳橙！花青素含量豐富，具有抗氧化、護心臟的功效。",
    tips: ["選蒂頭翠綠、果實飽滿鮮紅的", "尖端越紅表示熟成越好", "買回後不要清洗直接放冰箱，食用前再洗"]
  },
  {
    id: 3,
    fruit: "鳳梨",
    emoji: "🍍",
    title: "鳳梨酵素的神奇功效",
    category: "健康功效",
    content: "鳳梨含有獨特的鳳梨酵素（Bromelain），能幫助蛋白質消化，飯後吃鳳梨有助於腸胃道健康。金鑽鳳梨更是低纖維品種，過敏體質也能安心享用。",
    tips: ["切開後泡鹽水5分鐘可減少刺舌感", "冷藏後風味更甜", "鳳梨芯也可食用，富含酵素"]
  },
  {
    id: 4,
    fruit: "西瓜",
    emoji: "🍉",
    title: "如何挑選一顆甜西瓜",
    category: "挑選技巧",
    content: "西瓜含有茄紅素，是天然的抗氧化劑，同時水分含量高達92%，是夏日補水的最佳選擇。研究顯示西瓜中的瓜氨酸有助於改善血液循環。",
    tips: ["敲打聲音清脆空洞表示成熟", "底部黃色斑點越大越甜", "蒂頭捲曲、乾枯代表自然熟成"]
  },
  {
    id: 5,
    fruit: "香蕉",
    emoji: "🍌",
    title: "香蕉是天然的元氣棒",
    category: "健康功效",
    content: "香蕉富含鉀離子、鎂及維生素B6，能緩解肌肉疲勞，是運動後的最佳補給。色胺酸含量高，有助於血清素合成，改善情緒與睡眠品質。",
    tips: ["出現黑斑的香蕉甜度最高、最易消化", "綠色香蕉澱粉含量高，適合減重族", "放常溫讓其自然熟成，切勿冷藏未熟香蕉"]
  },
  {
    id: 6,
    fruit: "葡萄",
    emoji: "🍇",
    title: "葡萄皮的秘密",
    category: "營養知識",
    content: "葡萄皮中含有白藜蘆醇（Resveratrol），具有強效抗氧化功能，有助於護心健腦。花青素主要集中在果皮，連皮一起吃才能獲得完整營養。",
    tips: ["買回後浸泡鹽水10分鐘去農藥", "一串倒拿，從尾端開始吃最甜", "冷藏時不要清洗，保持乾燥延長保鮮"]
  },
  {
    id: 7,
    fruit: "梨山水蜜桃",
    emoji: "🍑",
    title: "梨山水蜜桃的高山奇蹟",
    category: "產地故事",
    content: "梨山位於台中市和平區，海拔約2000公尺，日夜溫差高達15°C以上，造就了水蜜桃無與倫比的甜度與香氣。梨山水蜜桃富含維生素C、β-胡蘿蔔素及膳食纖維，果肉柔軟易消化，是老人小孩都適合的營養水果。",
    tips: ["輕壓果頂有輕微彈性代表熟成恰好", "買回後放陰涼處1-2天讓香氣更濃", "冷藏後口感更佳，但不宜超過3天"]
  },
  {
    id: 8,
    fruit: "梨山蘋果",
    emoji: "🍎",
    title: "一天一蘋果，醫生遠離我",
    category: "健康功效",
    content: "梨山富士蘋果在高冷環境下生長，果實密實、糖酸比例完美。蘋果富含果膠（可溶性膳食纖維）、槲皮素及多酚類抗氧化物，有助於調節腸道健康、降低膽固醇。",
    tips: ["果皮含有大量營養，洗淨後連皮吃最好", "切開後泡鹽水或檸檬水防止氧化變褐", "存放冰箱冷藏可保鮮3-4週"]
  }
];
