// 水果資料庫
const fruitsData = [
  {
    id: 1,
    name: "台灣芒果",
    emoji: "🥭",
    price: 380,
    unit: "3公斤/箱",
    category: "熱帶水果",
    season: "5月-8月",
    origin: "屏東枋山",
    sugar: "18-22°Brix",
    description: "屏東在地金煌芒果，果肉厚實、纖維少，甜度爆表，每一口都是熱帶夏天的滋味。",
    tags: ["熱銷", "當季"],
    rating: 4.9,
    reviews: 328,
    inStock: true
  },
  {
    id: 2,
    name: "玉荷包荔枝",
    emoji: "🍒",
    price: 450,
    unit: "2公斤/盒",
    category: "夏季水果",
    season: "6月-7月",
    origin: "高雄大樹",
    sugar: "18-20°Brix",
    description: "高雄大樹玉荷包，果粒飽滿、殼薄肉厚，入口即化，是夏天最讓人期待的甜蜜滋味。",
    tags: ["限量", "當季"],
    rating: 4.8,
    reviews: 215,
    inStock: true
  },
  {
    id: 3,
    name: "鳳梨釋迦",
    emoji: "🍈",
    price: 520,
    unit: "4顆/盒",
    category: "熱帶水果",
    season: "10月-2月",
    origin: "台東太麻里",
    sugar: "20-24°Brix",
    description: "台東太麻里鳳梨釋迦，結合鳳梨與釋迦的甜蜜，果肉細緻、香氣濃郁，是送禮的最佳選擇。",
    tags: ["精品", "禮盒"],
    rating: 4.9,
    reviews: 189,
    inStock: true
  },
  {
    id: 4,
    name: "草莓",
    emoji: "🍓",
    price: 320,
    unit: "1公斤/盒",
    category: "溫帶水果",
    season: "12月-4月",
    origin: "苗栗大湖",
    sugar: "10-14°Brix",
    description: "苗栗大湖香水草莓，色澤鮮紅飽滿、香氣撲鼻，酸甜平衡，讓人忍不住一顆接一顆。",
    tags: ["熱銷", "當季"],
    rating: 4.7,
    reviews: 412,
    inStock: true
  },
  {
    id: 5,
    name: "香蕉",
    emoji: "🍌",
    price: 120,
    unit: "1串/約1.5公斤",
    category: "熱帶水果",
    season: "全年",
    origin: "南投集集",
    sugar: "14-18°Brix",
    description: "南投集集旗山蕉，果皮轉黃入口最甜，富含鉀離子，是運動後最好的天然補給品。",
    tags: ["天天到貨"],
    rating: 4.6,
    reviews: 567,
    inStock: true
  },
  {
    id: 6,
    name: "愛文芒果",
    emoji: "🥭",
    price: 420,
    unit: "4公斤/箱",
    category: "熱帶水果",
    season: "5月-8月",
    origin: "台南玉井",
    sugar: "16-20°Brix",
    description: "台南玉井愛文芒果，果皮紅豔鮮亮、果肉橙黃細膩，甜而不膩，是芒果族的最愛首選。",
    tags: ["熱銷", "當季"],
    rating: 4.8,
    reviews: 298,
    inStock: true
  },
  {
    id: 7,
    name: "巨峰葡萄",
    emoji: "🍇",
    price: 280,
    unit: "1公斤/盒",
    category: "溫帶水果",
    season: "7月-10月",
    origin: "彰化溪湖",
    sugar: "16-20°Brix",
    description: "彰化溪湖巨峰葡萄，顆粒碩大飽滿、果皮易剝，甜度高、汁液豐富，大人小孩都喜愛。",
    tags: ["當季"],
    rating: 4.7,
    reviews: 156,
    inStock: true
  },
  {
    id: 8,
    name: "鳳梨",
    emoji: "🍍",
    price: 160,
    unit: "1顆/約2公斤",
    category: "熱帶水果",
    season: "全年",
    origin: "嘉義民雄",
    sugar: "14-18°Brix",
    description: "嘉義民雄金鑽鳳梨，低纖維、無渣、多汁，甜度穩定，就算是對鳳梨過敏的人也能安心享用。",
    tags: ["天天到貨", "熱銷"],
    rating: 4.8,
    reviews: 445,
    inStock: true
  },
  {
    id: 9,
    name: "木瓜",
    emoji: "🧡",
    price: 180,
    unit: "1顆/約1.5公斤",
    category: "熱帶水果",
    season: "全年",
    origin: "台南玉井",
    sugar: "12-16°Brix",
    description: "台南玉井木瓜，果肉橙紅、質地細緻，富含木瓜酵素與維生素C，養顏美容的健康水果。",
    tags: ["健康首選"],
    rating: 4.6,
    reviews: 189,
    inStock: true
  },
  {
    id: 10,
    name: "西瓜",
    emoji: "🍉",
    price: 260,
    unit: "半顆/約5公斤",
    category: "夏季水果",
    season: "4月-9月",
    origin: "花蓮壽豐",
    sugar: "10-13°Brix",
    description: "花蓮壽豐無籽西瓜，果肉鮮紅、水分充足，夏日消暑的第一選擇，切開即享用超方便。",
    tags: ["當季", "消暑"],
    rating: 4.7,
    reviews: 234,
    inStock: true
  },
  {
    id: 11,
    name: "百香果",
    emoji: "🍋",
    price: 240,
    unit: "1公斤/約15顆",
    category: "熱帶水果",
    season: "7月-11月",
    origin: "南投埔里",
    sugar: "14-18°Brix",
    description: "南投埔里百香果，香氣濃郁撲鼻、酸甜恰到好處，可直接食用或調製成百香果汁，夏日消暑聖品。",
    tags: ["當季", "香氣濃"],
    rating: 4.8,
    reviews: 178,
    inStock: false
  },
  {
    id: 12,
    name: "蓮霧",
    emoji: "🔴",
    price: 350,
    unit: "2公斤/盒",
    category: "熱帶水果",
    season: "11月-2月",
    origin: "屏東林邊",
    sugar: "12-16°Brix",
    description: "屏東林邊黑珍珠蓮霧，外皮深紅油亮、果肉脆嫩多汁，入口清甜回甘，是台灣水果的驕傲。",
    tags: ["限量", "禮盒"],
    rating: 4.9,
    reviews: 267,
    inStock: true
  },

  // ===== 梨山高山水果 =====
  {
    id: 13,
    name: "梨山水蜜桃",
    emoji: "🍑",
    price: 680,
    unit: "12顆/盒",
    category: "梨山高山",
    season: "7月-9月",
    origin: "台中梨山",
    sugar: "14-18°Brix",
    description: "梨山高山水蜜桃，海拔2000公尺清涼山風孕育，果皮細薄、果肉如棉柔軟多汁，香甜滋味讓人魂牽夢縈。",
    tags: ["精品", "高山限定", "當季"],
    rating: 5.0,
    reviews: 312,
    inStock: true
  },
  {
    id: 14,
    name: "梨山富士蘋果",
    emoji: "🍎",
    price: 580,
    unit: "10顆/盒",
    category: "梨山高山",
    season: "10月-1月",
    origin: "台中梨山",
    sugar: "14-16°Brix",
    description: "梨山高冷富士蘋果，日夜溫差大造就甜度飽滿、果肉細密爽脆，每一口都是清甜的高山滋味。",
    tags: ["精品", "高山限定", "禮盒"],
    rating: 4.9,
    reviews: 256,
    inStock: true
  },
  {
    id: 15,
    name: "梨山梨子",
    emoji: "🍐",
    price: 520,
    unit: "8顆/盒",
    category: "梨山高山",
    season: "8月-10月",
    origin: "台中梨山",
    sugar: "12-15°Brix",
    description: "梨山高山水梨，果肉雪白細膩、水分充沛、清甜爽口，高山雲霧滋養讓風味格外清雅，是送禮首選。",
    tags: ["精品", "高山限定", "當季"],
    rating: 4.9,
    reviews: 198,
    inStock: true
  },
  {
    id: 16,
    name: "梨山甜柿",
    emoji: "🟠",
    price: 620,
    unit: "8顆/盒",
    category: "梨山高山",
    season: "10月-11月",
    origin: "台中梨山",
    sugar: "16-20°Brix",
    description: "梨山高山甜柿，海拔高、日照足，自然去澀不需處理，果肉橙黃飽滿、甜度極高，秋冬限定的山林珍品。",
    tags: ["限量", "高山限定", "當季"],
    rating: 4.9,
    reviews: 143,
    inStock: true
  },
  {
    id: 17,
    name: "梨山水蜜桃禮盒",
    emoji: "🎁",
    price: 1280,
    unit: "20顆/精裝禮盒",
    category: "梨山高山",
    season: "7月-9月",
    origin: "台中梨山",
    sugar: "16-20°Brix",
    description: "梨山頂級水蜜桃精裝禮盒，每顆經嚴格挑選，搭配精美禮盒包裝，是中秋送禮、孝親的最高規格選擇。",
    tags: ["精品", "禮盒", "送禮首選"],
    rating: 5.0,
    reviews: 89,
    inStock: true
  },
  {
    id: 18,
    name: "梨山高山水果組合",
    emoji: "🏔️",
    price: 960,
    unit: "蘋果+水梨+甜柿各4顆",
    category: "梨山高山",
    season: "10月-1月",
    origin: "台中梨山",
    sugar: "多種",
    description: "精選梨山三寶組合：富士蘋果、高山水梨、甜柿各四顆，一次品嚐梨山最精華的高山滋味，最受歡迎的伴手禮組合。",
    tags: ["精品", "禮盒", "組合優惠"],
    rating: 4.9,
    reviews: 167,
    inStock: true
  }
];

// 水果知識資料
const fruitKnowledge = [
  {
    id: 1,
    fruit: "芒果",
    emoji: "🥭",
    title: "芒果的營養秘密",
    category: "營養知識",
    content: "芒果富含維生素A、C、E及β-胡蘿蔔素，每100克含維生素C約36mg。其中的芒果苷具有抗氧化功效，適量食用有助於護眼、提升免疫力。",
    tips: ["挑選時以果皮光滑、按壓有彈性為佳", "放室溫等待轉黃再冷藏，甜度更高", "切忌未熟時冷藏，會影響後熟過程"]
  },
  {
    id: 2,
    fruit: "草莓",
    emoji: "🍓",
    title: "草莓挑選完全攻略",
    category: "挑選技巧",
    content: "草莓是維生素C的絕佳來源，每100克含量高達60mg，超過柳橙！花青素含量豐富，具有抗氧化、護心臟的功效。",
    tips: ["選蒂頭翠綠、果實飽滿鮮紅的", "尖端越紅表示熟成越好", "買回後不要清洗直接放冰箱，食用前再洗"]
  },
  {
    id: 3,
    fruit: "鳳梨",
    emoji: "🍍",
    title: "鳳梨酵素的神奇功效",
    category: "健康功效",
    content: "鳳梨含有獨特的鳳梨酵素（Bromelain），能幫助蛋白質消化，飯後吃鳳梨有助於腸胃道健康。金鑽鳳梨更是低纖維品種，過敏體質也能安心享用。",
    tips: ["切開後泡鹽水5分鐘可減少刺舌感", "冷藏後風味更甜", "鳳梨芯也可食用，富含酵素"]
  },
  {
    id: 4,
    fruit: "西瓜",
    emoji: "🍉",
    title: "如何挑選一顆甜西瓜",
    category: "挑選技巧",
    content: "西瓜含有茄紅素，是天然的抗氧化劑，同時水分含量高達92%，是夏日補水的最佳選擇。研究顯示西瓜中的瓜氨酸有助於改善血液循環。",
    tips: ["敲打聲音清脆空洞表示成熟", "底部黃色斑點越大越甜", "蒂頭捲曲、乾枯代表自然熟成"]
  },
  {
    id: 5,
    fruit: "香蕉",
    emoji: "🍌",
    title: "香蕉是天然的元氣棒",
    category: "健康功效",
    content: "香蕉富含鉀離子、鎂及維生素B6，能緩解肌肉疲勞，是運動後的最佳補給。色胺酸含量高，有助於血清素合成，改善情緒與睡眠品質。",
    tips: ["出現黑斑的香蕉甜度最高、最易消化", "綠色香蕉澱粉含量高，適合減重族", "放常溫讓其自然熟成，切勿冷藏未熟香蕉"]
  },
  {
    id: 6,
    fruit: "葡萄",
    emoji: "🍇",
    title: "葡萄皮的秘密",
    category: "營養知識",
    content: "葡萄皮中含有白藜蘆醇（Resveratrol），具有強效抗氧化功能，有助於護心健腦。花青素主要集中在果皮，連皮一起吃才能獲得完整營養。",
    tips: ["買回後浸泡鹽水10分鐘去農藥", "一串倒拿，從尾端開始吃最甜", "冷藏時不要清洗，保持乾燥延長保鮮"]
  },
  {
    id: 7,
    fruit: "梨山水蜜桃",
    emoji: "🍑",
    title: "梨山水蜜桃的高山奇蹟",
    category: "產地故事",
    content: "梨山位於台中市和平區，海拔約2000公尺，日夜溫差高達15°C以上，造就了水蜜桃無與倫比的甜度與香氣。梨山水蜜桃富含維生素C、β-胡蘿蔔素及膳食纖維，果肉柔軟易消化，是老人小孩都適合的營養水果。",
    tips: ["輕壓果頂有輕微彈性代表熟成恰好", "買回後放陰涼處1-2天讓香氣更濃", "冷藏後口感更佳，但不宜超過3天"]
  },
  {
    id: 8,
    fruit: "梨山蘋果",
    emoji: "🍎",
    title: "一天一蘋果，醫生遠離我",
    category: "健康功效",
    content: "梨山富士蘋果在高冷環境下生長，果實密實、糖酸比例完美。蘋果富含果膠（可溶性膳食纖維）、槲皮素及多酚類抗氧化物，有助於調節腸道健康、降低膽固醇。",
    tips: ["果皮含有大量營養，洗淨後連皮吃最好", "切開後泡鹽水或檸檬水防止氧化變褐", "存放冰箱冷藏可保鮮3-4週"]
  }
];
